In [253]:
5 + 5

10

In [3]:
5 - 5

0

In [4]:
5 ++ 5

10

In [5]:
5 -- 5 

10

In [6]:
5 / 2

2.5

In [7]:
5 // 2  # // is Floor, Int Out

2

In [9]:
1243 // 100

12

In [14]:
(1243 // 100) % 10

2

In [15]:
5 * 2

10

In [17]:
5 ** 2 # power 5^2

25

In [18]:
#### WE HAVE Data but in our Mind.. How to Store Data 

In [25]:
x = 5

In [26]:
y = x

In [27]:
id(5)

4394460416

In [28]:
id(x)

4394460416

In [29]:
id(y)

4394460416

In [30]:
y = 6

In [31]:
id(y)

4394460448

In [34]:
### Data Type in Python - int, floot, str
# Note - we don't have to Def...

In [39]:
x = "4"

In [41]:
type(x)

str

In [44]:
x = 5
y = '12'

In [46]:
## Type Casting
## fun - int, float, str

## int -> str = str(intData)
## str -> float = float(strData)
## str -> int = int(strData)


In [49]:
y = int(y)

In [51]:
x + y

17

In [52]:
x = "Todays Temp is:"
y = 12

In [54]:
x + " " + str(y)

'Todays Temp is: 12'

In [61]:
x = "3.4"

In [63]:
int(float(x))

3

In [65]:
x = 5
y = 3

print(x + y)
print(x - y)

8
2


In [69]:
x = "Todads Temp is:"
y = 32
print(x,y, 32342.32423, "Hello")

Todads Temp is: 32 32342.32423 Hello


In [70]:
### Cal...
## input(Number) from User....

In [76]:
x = input()

Hello


In [78]:
type(x)

str

In [83]:
x = int(input("Value 1: "))
y = int(input("Value 2: "))

x + y

Value 1: 4
Value 2: 6


10

In [84]:
#### Play with Strings....

In [85]:
x = "Hello Python"

In [87]:
len(x)

12

In [88]:
### index - 0 -> 

In [93]:
### Slicing --- var[start:stop+1]

('H', 'e', 'l')

In [95]:
x[0:5]

'Hello'

In [98]:
#### Array or List

In [225]:
x = [12,32,324,43,34,43,21]

In [104]:
x[:3]

[12, 32, 324]

In [226]:
"""
Fun of List.
    1. append - add new value last of list.
    2. insert - add new value any pos..
    3. index - find index number of any value
    4. remove, pop
    5. reverse,
    6. sort - arange your data in as, de order.. 
"""

'\nFun of List.\n    1. append - add new value last of list.\n    2. insert - add new value any pos..\n    3. index - find index number of any value\n    4. remove, pop\n    5. reverse,\n    6. sort - arange your data in as, de order..\n    7. pop and remove \n'

In [108]:
x = [12,33,4,54,66, 78,12]

In [109]:
maxAcc = max(x)

In [130]:
# List.fun(arg) 

x.index(maxAcc)

5

In [228]:
#### Ex of Append Fun..
dataBase = []

In [232]:
name = input("Your Name:")
dataBase.append(name)

Your Name:Kedar


In [237]:
dataBase

['Nikita', 'Kedar']

In [234]:
dataBase.pop(1)

'Rahul'

In [236]:
dataBase.remove("Prateek")

In [143]:
x = [12,33,4,54,66, 78,12]

In [174]:
# Shift + Tab for Arg Info inside any fun, class
x.insert(2, 23)

In [139]:
### sort, sorted

In [147]:
x

[4, 12, 12, 23, 33, 54, 66, 78]

In [148]:
x.sort()
x

[4, 12, 12, 23, 33, 54, 66, 78]

In [149]:
x = [12,33,4,54,66, 78,12]

In [154]:
y = sorted(x)
y

[4, 12, 12, 33, 54, 66, 78]

In [158]:
x

[12, 33, 4, 54, 66, 78, 12]

In [156]:
y.reverse()

In [157]:
y

[78, 66, 54, 33, 12, 12, 4]

In [175]:
## Con Stat... if-elif-else

In [187]:
x = int(input("Enter Any Value: "))
if x == 5:
    print("Correct Pass...")
    print("Welcome Prateek...")
else:
    print("Your Entered Wrong Pass...")
    

Enter Any Value: 12
Your Entered Wrong Pass...


In [190]:
### Loop - for and while

In [238]:
for i in range(6):
    print("Welcome to TechSim+")
    print("MLOPS Class..")

Welcome to TechSim+
MLOPS Class..
Welcome to TechSim+
MLOPS Class..
Welcome to TechSim+
MLOPS Class..
Welcome to TechSim+
MLOPS Class..
Welcome to TechSim+
MLOPS Class..
Welcome to TechSim+
MLOPS Class..


In [200]:
for i in range(5, 10, 1):
    print(i)

5
6
7
8
9


In [202]:
for i in range(9, 4, -1):
    print(i)
    

9
8
7
6
5


In [244]:
### program is: take 5 input from user - entered number should be 3
x = [1]
Data = []
for i in x:
    n = int(input("Enter 3: "))
    if n == 3:
        Data.append(n)
    if len(Data) == 5:
        break
    x.append(i)


Enter 3: 2
Enter 3: 3
Enter 3: 4
Enter 3: 5
Enter 3: 6
Enter 3: 3
Enter 3: 3
Enter 3: 1
Enter 3: 4
Enter 3: 3
Enter 3: 3


In [206]:
x = 0
while x < 5:
    n = int(input("Num: "))
    if n is 3:
        x = x + 1
    

Num: 2
Num: 2
Num: 1
Num: 3
Num: 2
Num: 2
Num: 2
Num: 2
Num: 2
Num: 2
Num: 2
Num: 22
Num: 2
Num: 2
Num: 2
Num: 2
Num: 22
Num: 2
Num: 3
Num: 3
Num: 3
Num: 3


In [173]:
### append, input, sort(key - Con), forloop ifelse

In [210]:
dataBase = []
for i in range(5):
    print("Welcome to TechSim+. Register Here...")
    name = input("Enter Your Name: ")
    dataBase.append(name)

sorted(dataBase, key = len, reverse = True)
    

Welcome to TechSim+. Register Here...
Enter Your Name: hbjhbk
Welcome to TechSim+. Register Here...
Enter Your Name: bjb
Welcome to TechSim+. Register Here...
Enter Your Name: ihi
Welcome to TechSim+. Register Here...
Enter Your Name: n
Welcome to TechSim+. Register Here...
Enter Your Name: jbkkjbkn


['jbkkjbkn', 'hbjhbk', 'bjb', 'ihi', 'n']

In [211]:
##### Name, Number, Email

In [217]:
dataBase = []
for i in range(2):
    name = input("Name:")
    Number = input("Number:")
    Email = input("Email:")
    
    
    data = [name, Number, Email]
    dataBase.append(data)

Name:Prateek
Number:87897
Email:bbbkib
Name:Rahul
Number:98797
Email:jbj


In [221]:
dataBase

[['Prateek', '87897', 'bbbkib'], ['Rahul', '98797', 'jbj']]

In [224]:
dataBase[0][2]

'bbbkib'

In [245]:
##### Dict - List (Array), Set, Tuple, Dict

In [264]:
## image1.jpg (Dog), image2.jpg (Cat) 

x = {
    "Dog":"image1.jpg", "Cat":"image2.jpg", "Dog":"img.jpg"
}

In [266]:
x["Pandas"] = "image3.jpg"

In [269]:
x["dog"] = "image.jpg"

In [273]:
x

{'Dog': 'image4.jpg',
 'Cat': 'image2.jpg',
 'Pandas': 'image3.jpg',
 'dog': 'image.jpg'}

In [275]:
for i in x:
    print(i, "-->", x[i])

Dog --> image4.jpg
Cat --> image2.jpg
Pandas --> image3.jpg
dog --> image.jpg


In [282]:
Out = {"file":"image.jpg", "dog":0.09, "cat":0.91}

In [283]:
if Out["dog"] > Out["cat"]:
    print("Its Dog")
else:
    print("Its Cat")

Its Cat


In [284]:
#### Registration System

In [290]:
DataBase = {"Name":[], "Email":[], "Age":[]}

In [291]:
for i in range(5):
    name = input("Your Name: ")
    Age = input("Age:")
    Email = input("Email:")
    
    DataBase["Name"].append(name)
    DataBase["Age"].append(Age)
    DataBase["Email"].append(Email)

Your Name: Prateek
Age:26
Email:p@g.com
Your Name: Rahul
Age:7y8
Email:jkbjkkb
Your Name: bhjbjj
Age:jhkih
Email:jhnkjnk
Your Name: bjknkj
Age:nkjnhkj
Email:bjkbkj
Your Name: bjknkjnb
Age:bjbnkjn
Email:bknk


In [296]:
DataBase

{'Name': ['Prateek', 'Rahul', 'bhjbjj', 'bjknkj', 'bjknkjnb'],
 'Email': ['p@g.com', 'jkbjkkb', 'jhnkjnk', 'bjkbkj', 'bknk'],
 'Age': ['26', '7y8', 'jhkih', 'nkjnhkj', 'bjbnkjn']}

In [298]:
Z = DataBase["Name"].index("Rahul")
DataBase["Email"][Z]

'jkbjkkb'

In [309]:
Iris = [23,4,43,54,6,54,65,43,46,56,535,54,546,5,32,32,2,3]

In [310]:
Class = {"C1":[], "C2":[]}

In [311]:
for i in Iris:
    if i>=100:
        Class["C2"].append(i)
    else:
        Class["C1"].append(i)

In [312]:
Class

{'C1': [23, 4, 43, 54, 6, 54, 65, 43, 46, 56, 54, 5, 32, 32, 2, 3],
 'C2': [535, 546]}

In [314]:
#### Import Lib.. Random

In [333]:
import random as rd

In [334]:
# randint

rd.randint(0, 21)

21

In [335]:
rd.randint(12,45)

21

In [337]:
## import randint direct
from random import randint as ri

In [338]:
ri(23,45)

32

In [353]:
#### Def Fun...
from time import sleep

In [360]:
def Train(train, test):
    print("We are Training Your Machine with", train)
    sleep(4)
    print("Its Done..!!")
    return test*2

In [362]:
out = Train(43, 12)

We are Training Your Machine with 43
Its Done..!!


In [363]:
out

24

In [1]:
import Calculator

In [4]:
Calculator.Cal(3,4,'+')

7


In [5]:
import os

In [6]:
os.mkdir("Images")

In [42]:
Data = [
    [23,33.3,33,44,4],
    [213,32,32,3,3],
    [55,66,44,66,7]
]
len(Data)

3

In [23]:
# Q - Find Min Max and Mean (AV)
#    1. For all data.
#    2. For Row Wise
    

In [21]:
## Solve:
# 2. For Row Wise

for i in Data:
    print("Min:",min(i), "-->Max:", max(i), "-->Mean:", sum(i)/len(i))



Min: 4 -->Max: 44 -->Mean: 27.46
Min: 3 -->Max: 213 -->Mean: 56.6
Min: 7 -->Max: 66 -->Mean: 47.6


In [22]:
# 3. For Col Wise

for col in range(5):
    data = []
    for row in range(3):
        data.append(Data[row][col])
    print("Min:",min(data), "-->Max:", max(data), "-->Mean:", sum(data)/len(data))

Min: 23 -->Max: 213 -->Mean: 97.0
Min: 32 -->Max: 66 -->Mean: 43.76666666666667
Min: 32 -->Max: 44 -->Mean: 36.333333333333336
Min: 3 -->Max: 66 -->Mean: 37.666666666666664
Min: 3 -->Max: 7 -->Mean: 4.666666666666667


### Numpy - Array

In [26]:
import numpy as np

In [39]:
a = [4,3,4,323,4.1,443,32]
a

[4, 3, 4, 323, 4.1, 443, 32]

In [40]:
## convert this LIst in Array
Array = np.array(a)

In [41]:
Array

array([  4. ,   3. ,   4. , 323. ,   4.1, 443. ,  32. ])

In [43]:
## Len, Shape, Size

In [45]:
Array.shape

(7,)

In [57]:
Array = np.array([
    [2,132,3,15],
    [32,32,32, 67],
    [32,32,32,30]
])

In [58]:
Array.shape

(3, 4)

In [60]:
np.ndim(Array) # Array.ndim

2

In [61]:
Array

array([[  2, 132,   3,  15],
       [ 32,  32,  32,  67],
       [ 32,  32,  32,  30]])

In [79]:
Array[0:1, 1:3]

array([[132,   3]])

In [101]:
Array[1:3, 1:3] = ((120, 11), (43, 9))

In [103]:
Array

array([[  2, 132,   3,  15],
       [ 32, 120,  11,  67],
       [ 32,  43,   9,  30]])

In [73]:
a[10:12]

[]

In [84]:
Array

array([[  2, 132,   3,  15],
       [ 32,  12,  54,  67],
       [ 32,  43,   9,  30]])

In [90]:
Array.min(axis = 1) ## 0 - cols, 1 - Rows

array([ 2, 12,  9])

In [91]:
Array.max(axis = 0)

array([ 32, 132,  54,  67])

In [92]:
Array.mean(axis = 0)

array([22.        , 62.33333333, 22.        , 37.33333333])

In [93]:
#### Find Top  Student in Class

In [123]:
StudentsScores = {"Name":["Prateek", "Nikita", "Rahul", "Mohit", "Manas"], 
                  "Marks": np.array([90, 88, 87, 94, 91])}

In [114]:
StudentsScores["Name"][StudentsScores["Marks"].argmax()]

'Mohit'

In [124]:
A = StudentsScores["Marks"]
A

array([90, 88, 87, 94, 91])

In [126]:
Array

array([[  2, 132,   3,  15],
       [ 32, 120,  11,  67],
       [ 32,  43,   9,  30]])

In [127]:
# (1,12), (12,1), (4,3), (2,6), (6,2)

In [133]:
Array.reshape((2,6))

array([[  2, 132,   3,  15,  32, 120],
       [ 11,  67,  32,  43,   9,  30]])

In [142]:
Array.reshape((6, -1))

array([[  2, 132],
       [  3,  15],
       [ 32, 120],
       [ 11,  67],
       [ 32,  43],
       [  9,  30]])

In [144]:
Array.T

array([[  2,  32,  32],
       [132, 120,  43],
       [  3,  11,   9],
       [ 15,  67,  30]])

In [148]:
Array.reshape((4,3))

array([[  2, 132,   3],
       [ 15,  32, 120],
       [ 11,  67,  32],
       [ 43,   9,  30]])

In [152]:
np.random.permutation(5)

array([1, 0, 4, 3, 2])

In [ ]:
##. Hours, Marks 

In [157]:
Da = np.array([
    [1, 10],
    [2, 20],
    [2.3, 25],
    [4, 45],
]
)

In [158]:
Da

array([[ 1. , 10. ],
       [ 2. , 20. ],
       [ 2.3, 25. ],
       [ 4. , 45. ]])

In [164]:
Sf = np.random.permutation(len(Da))

In [165]:
Da[Sf]

array([[ 2.3, 25. ],
       [ 2. , 20. ],
       [ 4. , 45. ],
       [ 1. , 10. ]])

## Day - 11