In [7]:
from random import choice
from numpy import array, dot, random
import numpy as np

In [8]:
## AND Gate

In [17]:
training_data = [
    (array([0, 0]), 0),
    (array([0, 1]), 0),
    (array([1, 0]), 0),
    (array([1, 1]), 1),
]

w = [1, 1]

def step_function(x):
    if x<2:
        return 0
    else:
        return 1

for ind,dep in training_data:
    result = sum(ind)
    #result = dot(ind, w)
    out = step_function(result)
    print(ind, '-->', out, result)

[0 0] --> 0 0
[0 1] --> 0 1
[1 0] --> 0 1
[1 1] --> 1 2


In [18]:
### Rosenblatt's Perceptron

In [30]:
training_data = [
    (array([0, 0, 1]), 0),
    (array([0, 1, 1]), 0),
    (array([1, 0, 1]), 0),
    (array([1, 1, 1]), 1),
]


def step_function(x):
    if x<2:
        return 0
    else:
        return 1
    
w = [1, 1, 1]
errors = []
lr = 0.1
n = 5000

for i in range(n):
    error = 0
    for ind, expected in training_data:
        result = dot(ind,w)
        predict = step_function(result)
        e = expected- predict
        error +=e
    errors.append(error)
    w = w + (lr*error*ind) #optimising algo - GD
    w[0] = 9
    if error == 0:
        print(i)
        break
print(w)

for ind,dep in training_data:
    result = sum(ind)
    #result = dot(ind, w)
    out = step_function(result)
    print(ind, '-->', out)

44
[ 9.  -3.5 -3.5]
[0 0 1] --> 0
[0 1 1] --> 1
[1 0 1] --> 1
[1 1 1] --> 1
