In [3]:
from sklearn.linear_model import LogisticRegression, LinearRegression
import pandas as pd
import numpy as np

In [4]:
##e = 2.71828
##g = 1/(1+e**-y)

In [5]:
df=pd.read_csv("loanf.csv")

In [6]:
df.keys()

Index(['Interest.Rate', 'FICO.Score', 'Loan.Length', 'Monthly.Income',
       'Loan.Amount'],
      dtype='object')

In [7]:
df.shape
df["NewIntrest"] = df["Interest.Rate"] < 17

In [8]:
x = df[["FICO.Score", "Loan.Amount"]]

In [9]:
y = df["Interest.Rate"]

In [10]:
y

6       15.31
11      19.72
12      14.27
13      21.67
21      21.98
        ...  
2472     7.90
2481     6.03
2482     6.62
2486    10.75
2497    14.09
Name: Interest.Rate, Length: 2500, dtype: float64

In [11]:
y = df["NewIntrest"]

In [12]:
y

6        True
11      False
12       True
13      False
21      False
        ...  
2472     True
2481     True
2482     True
2486     True
2497     True
Name: NewIntrest, Length: 2500, dtype: bool

In [13]:
x = df[["FICO.Score","Loan.Amount"]].values
y = df["Interest.Rate"]

In [14]:
model = LinearRegression()
model = model.fit(x,y)

In [15]:
## Logistic Regression

In [16]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

In [17]:
df=pd.read_csv("loanf.csv")

In [18]:
df["NewIntrest"] = df["Interest.Rate"] < 17
x = df[["FICO.Score", "Loan.Amount"]]
y = df["NewIntrest"]

In [19]:
df.NewIntrest.value_counts()

True     2032
False     468
Name: NewIntrest, dtype: int64

In [20]:
log_model = LogisticRegression()
log_model = log_model.fit(x,y)

In [21]:
log_model.predict([[14,2000]])

array([False])

In [22]:
log_model.predict_proba([[14, 20000]])

array([[0.88621131, 0.11378869]])

In [23]:
type(log_model)

sklearn.linear_model._logistic.LogisticRegression

In [24]:
def Loan_Approval_or_Not(FICO, Amount):
    out = log_model.predict_proba([[FICO, Amount]])
    if out[0][1]>0.8:
        print("Loan will Approve")
    else:
        print('Not Approve')

In [25]:
from ipywidgets import interact

In [26]:
interact(Loan_Approval_or_Not, FICO=(50,1200), Amount=(200, 100000))

interactive(children=(IntSlider(value=625, description='FICO', max=1200, min=50), IntSlider(value=50100, descr…

<function __main__.Loan_Approval_or_Not(FICO, Amount)>

In [27]:
### Accuracy Score

In [28]:
pred_loan = log_model.predict(x)

In [29]:
pred_loan

array([ True,  True,  True, ...,  True,  True,  True])

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [31]:
accuracy_score(y, pred_loan)

0.8272

In [32]:
confusion_matrix(y, pred_loan)

array([[  75,  393],
       [  39, 1993]], dtype=int64)

In [33]:
(75+1993)/(75+393+39+1993)

0.8272

In [34]:
def Accuract_Score(act, pred):
    act = np.array(act)
    pred = np.array(pred)
    total_correct = 0
    if len(act) == len(pred):
        for i in range(len(act)):
            if act[i] == pred[i]:
                total_correct +=1
        print("A", total_correct/len(act))
    else:
        print(". {} -- {}".format(act.shape, pred))

#(list(np.array(y==pred_loan)).count(True))/len(y)

In [35]:
Accuract_Score(y, pred_load)

NameError: name 'pred_load' is not defined

In [36]:
##### Task is: create confusion_matrix function

In [37]:
####Important Topic#######

In [38]:
# client point of view

# Save Your Trained Model

In [1]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (c:\users\anshu\appdata\local\programs\python\python38\lib\site-packages\sklearn\externals\__init__.py)

In [ ]:
joblib.dump(log_mode, "loan_approve_or_not.pkl")